In [1]:
import numpy as np
import math
from math import e

# Convolution

x_n=[1,-2,1]
h_n=[1,1,1,1,1,1]

y_n=np.convolve(x_n,h_n)

y_n


array([ 1, -1,  0,  0,  0,  0, -1,  1])

In [2]:
#cross correlation 

x_n=[2, -1,3.7,1,2,-3]
y_n=[1, -1, 2, -2,4,1, -2,5]

ans=np.correlate(x_n,y_n,mode='full')
ans

array([ 10. ,  -9. ,  22.5,   4.6,   3.7,   2.8,   0.6,  13.4, -18.7,
        12.7,  -7. ,   5. ,  -3. ])

In [17]:
# circular convolution

a=[1,2,3,0,0,0,0,0]
b=[1,2,2,1,0,0,0,0]

n = len(a)
ans=np.convolve(np.tile(a, 2), b)[n:2 * n]


ans

array([ 1,  4,  9, 11,  8,  3,  0,  0])

In [15]:
# exponential 


ans= e**((0-1j)*math.pi*1.5)

ans

(-1.8369701987210297e-16+1j)

In [26]:
# N point DFT calculation

# Make sure the list/array is of length N 

ans= np.fft.fft(b)

for i in ans:
    print(i)

(6+0j)
(1.7071067811865475-4.121320343559643j)
(-1-1j)
(0.2928932188134524-0.12132034355964283j)
0j
(0.2928932188134524+0.12132034355964283j)
(-1+1j)
(1.7071067811865475+4.121320343559643j)
